// This file contains all the data for the vowel game
// Each object in the array represents a single vowel sound

export const VOWEL_DATA = [
    // Acorn - long "a" sound /eɪ/
    {
        name: "acorn",
        symbol: "eɪ",
        // NOTE: The vowelAudio property is now redundant, but kept for reference
        vowelAudio: "audio/acorn/ae.m4a",
        words: [
            // *** CRITICAL ADDITION FOR VOWEL INTRO AUDIO AND GAME FILTERING ***
            { word: "vowel sound", audio: "audio/acorn/acorn_vowel_sound_only.m4a" },
            { word: "great", audio: "audio/acorn/great.m4a" },
            { word: "hate", audio: "audio/acorn/hate.m4a" },
            { word: "jail", audio: "audio/acorn/jail.m4a" },
            { word: "lane", audio: "audio/acorn/lane.m4a" },
            { word: "late", audio: "audio/acorn/late.m4a" },
            { word: "main", audio: "audio/acorn/main.m4a" },
            { word: "may", audio: "audio/acorn/may.m4a" },
            { word: "nay", audio: "audio/acorn/nay.m4a" },
            { word: "pay", audio: "audio/acorn/pay.m4a" },
            { word: "quake", audio: "audio/acorn/quake.m4a" },
            { word: "rain", audio: "audio/acorn/rain.m4a" },
            { word: "say", audio: "audio/acorn/say.m4a" },
            { word: "shape", audio: "audio/acorn/shape.m4a" },
            { word: "tame", audio: "audio/acorn/tame.m4a" },
            { word: "thank", audio: "audio/acorn/thank.m4a" },
            { word: "vape", audio: "audio/acorn/vape.m4a" },
            { word: "wait", audio: "audio/acorn/wait.m4a" },
            { word: "yea", audio: "audio/acorn/yea.m4a" },
            { word: "zane", audio: "audio/acorn/zane.m4a" },
            { word: "ace", audio: "audio/acorn/ace.m4a" },
            { word: "ae", audio: "audio/acorn/ae.m4a" },
            { word: "bait", audio: "audio/acorn/bait.m4a" },
            { word: "cake", audio: "audio/acorn/cake.m4a" },
            { word: "change", audio: "audio/acorn/change.m4a" },
            { word: "day", audio: "audio/acorn/day.m4a" },
            { word: "fake", audio: "audio/acorn/fake.m4a" }
        ],
        image: "images/vowel_card_acorn.jpg"
    },

    // Alligator - short "a" sound /æ/
    {
        name: "aligator",
        symbol: "æ",
        vowelAudio: "audio/aligator/aa.m4a",
        words: [
            // *** CRITICAL ADDITION ***
            { word: "vowel sound", audio: "audio/aligator/aligator_vowel_sound_only.m4a" },
            { word: "axe", audio: "audio/aligator/axe.m4a" },
            { word: "bag", audio: "audio/aligator/bag.m4a" },
            { word: "bat", audio: "audio/aligator/bat.m4a" },
            { word: "cat", audio: "audio/aligator/cat.m4a" },
            { word: "chap", audio: "audio/aligator/chap.m4a" },
            { word: "dad", audio: "audio/aligator/dad.m4a" },
            { word: "fat", audio: "audio/aligator/fat.m4a" },
            { word: "grab", audio: "audio/aligator/grab.m4a" },
            { word: "hat", audio: "audio/aligator/hat.m4a" },
            { word: "jacks", audio: "audio/aligator/jacks.m4a" },
            { word: "lad", audio: "audio/aligator/lad.m4a" },
            { word: "mat", audio: "audio/aligator/mat.m4a" },
            { word: "nan", audio: "audio/aligator/nan.m4a" },
            { word: "patch", audio: "audio/aligator/patch.m4a" },
            { word: "quack", audio: "audio/aligator/quack.m4a" },
            { word: "rad", audio: "audio/aligator/rad.m4a" },
            { word: "sap", audio: "audio/aligator/sap.m4a" },
            { word: "shack", audio: "audio/aligator/shack.m4a" },
            { word: "tax", audio: "audio/aligator/tax.m4a" },
            { word: "that", audio: "audio/aligator/that.m4a" },
            { word: "vast", audio: "audio/aligator/vast.m4a" },
            { word: "vat", audio: "audio/aligator/vat.m4a" },
            { word: "yeah", audio: "audio/aligator/yeah.m4a" },
            { word: "zap", audio: "audio/aligator/zap.m4a" },
            { word: "aa", audio: "audio/aligator/aa.m4a" }
        ],
        image: "images/vowel_card_aligator.jpg"
    },

    // Australia - short "o" sound /ɔ/
    {
        name: "australia",
        symbol: "ɔ",
        vowelAudio: "audio/australia/au.m4a",
        words: [
            // *** CRITICAL ADDITION ***
            { word: "vowel sound", audio: "audio/australia/australia_vowel_sound_only.m4a" },
            { word: "ball", audio: "audio/australia/ball.m4a" },
            { word: "call", audio: "audio/australia/call.m4a" },
            { word: "caught", audio: "audio/australia/caught.m4a" },
            { word: "dog", audio: "audio/australia/dog.m4a" },
            { word: "fall", audio: "audio/australia/fall.m4a" },
            { word: "far", audio: "audio/australia/far.m4a" },
            { word: "gall", audio: "audio/australia/gall.m4a" },
            { word: "haul", audio: "audio/australia/haul.m4a" },
            { word: "hog", audio: "audio/australia/hog.m4a" },
            { word: "jaw", audio: "audio/australia/jaw.m4a" },
            { word: "law", audio: "audio/australia/law.m4a" },
            { word: "log", audio: "audio/australia/log.m4a" },
            { word: "maude", audio: "audio/australia/maude.m4a" },
            { word: "moth", audio: "audio/australia/moth.m4a" },
            { word: "naught", audio: "audio/australia/naught.m4a" },
            { word: "pause", audio: "audio/australia/pause.m4a" },
            { word: "paw", audio: "audio/australia/paw.m4a" },
            { word: "quant", audio: "audio/australia/quant.m4a" },
            { word: "raw", audio: "audio/australia/raw.m4a" },
            { word: "rob", audio: "audio/australia/rob.m4a" },
            { word: "saw", audio: "audio/australia/saw.m4a" },
            { word: "sob", audio: "audio/australia/sob.m4a" },
            { word: "tall", audio: "audio/australia/tall.m4a" },
            { word: "thaw", audio: "audio/australia/thaw.m4a" },
            { word: "thought", audio: "audio/australia/thought.m4a" },
            { word: "vaughn", audio: "audio/australia/vaughn.m4a" },
            { word: "walk", audio: "audio/australia/walk.m4a" },
            { word: "wall", audio: "audio/australia/wall.m4a" },
            { word: "wash", audio: "audio/australia/wash.m4a" },
            { word: "yall", audio: "audio/australia/yall.m4a" },
            { word: "yawn", audio: "audio/australia/yawn.m4a" },
            { word: "zod", audio: "audio/australia/zod.m4a" },
            { word: "zogg", audio: "audio/australia/zogg.m4a" },
            { word: "all", audio: "audio/australia/all.m4a" },
            { word: "au", audio: "audio/australia/au.m4a" },
            { word: "a", audio: "audio/australia/a.m4a" }
        ],
        image: "images/vowel_card_australia.jpg"
    },

    // Eagle - long "e" sound /i/
    {
        name: "eagle",
        symbol: "i",
        vowelAudio: "audio/eagle/ee.m4a",
        words: [
            // *** CRITICAL ADDITION ***
            { word: "vowel sound", audio: "audio/eagle/eagle_vowel_sound_only.m4a" },
            { word: "easy", audio: "audio/eagle/easy.m4a" },
            { word: "ee", audio: "audio/eagle/ee.m4a" },
            { word: "feet", audio: "audio/eagle/feet.m4a" },
            { word: "green", audio: "audio/eagle/green.m4a" },
            { word: "heel", audio: "audio/eagle/heel.m4a" },
            { word: "jeans", audio: "audio/eagle/jeans.m4a" },
            { word: "king", audio: "audio/eagle/king.m4a" },
            { word: "leaf", audio: "audio/eagle/leaf.m4a" },
            { word: "meet", audio: "audio/eagle/meet.m4a" },
            { word: "near", audio: "audio/eagle/near.m4a" },
            { word: "peach", audio: "audio/eagle/peach.m4a" },
            { word: "queen", audio: "audio/eagle/queen.m4a" },
            { word: "read", audio: "audio/eagle/read.m4a" },
            { word: "see", audio: "audio/eagle/see.m4a" },
            { word: "sheep", audio: "audio/eagle/sheep.m4a" },
            { word: "tea", audio: "audio/eagle/tea.m4a" },
            { word: "three", audio: "audio/eagle/three.m4a" },
            { word: "veer", audio: "audio/eagle/veer.m4a" },
            { word: "beat", audio: "audio/eagle/beat.m4a" },
            { word: "cream", audio: "audio/eagle/cream.m4a" },
            { word: "deer", audio: "audio/eagle/deer.m4a" },
            { word: "feet", audio: "audio/eagle/feet.m4a" },
            { word: "greek", audio: "audio/eagle/greek.m4a" },
            { word: "wheat", audio: "audio/eagle/wheat.m4a" },
            { word: "wheel", audio: "audio/eagle/wheel.m4a" },
            { word: "yeet", audio: "audio/eagle/yeet.m4a" },
            { word: "zeek", audio: "audio/eagle/zeek.m4a" },
            { word: "beam", audio: "audio/eagle/beam.m4a" },
            { word: "cheat", audio: "audio/eagle/cheat.m4a" },
            { word: "cream", audio: "audio/eagle/cream.m4a" }
        ],
        image: "images/vowel_card_eagle.jpg"
    },

    // Earth - "ur" sound /ɜː/
    {
        name: "earth",
        symbol: "ɜː",
        vowelAudio: "audio/earth/er.m4a",
        words: [
            // *** CRITICAL ADDITION ***
            { word: "vowel sound", audio: "audio/earth/earth_vowel_sound_only.m4a" },
            { word: "dirt", audio: "audio/earth/dirt.m4a" },
            { word: "earn", audio: "audio/earth/earn.m4a" },
            { word: "earth", audio: "audio/earth/earth.m4a" },
            { word: "er", audio: "audio/earth/er.m4a" },
            { word: "first", audio: "audio/earth/first.m4a" },
            { word: "girth", audio: "audio/earth/girth.m4a" },
            { word: "hurt", audio: "audio/earth/hurt.m4a" },
            { word: "jerk", audio: "audio/earth/jerk.m4a" },
            { word: "kirk", audio: "audio/earth/kirk.m4a" },
            { word: "learn", audio: "audio/earth/learn.m4a" },
            { word: "lurch", audio: "audio/earth/lurch.m4a" },
            { word: "merch", audio: "audio/earth/merch.m4a" },
            { word: "nurse", audio: "audio/earth/nurse.m4a" },
            { word: "purse", audio: "audio/earth/purse.m4a" },
            { word: "quirk", audio: "audio/earth/quirk.m4a" },
            { word: "shirt", audio: "audio/earth/shirt.m4a" },
            { word: "sir", audio: "audio/earth/sir.m4a" },
            { word: "thirst", audio: "audio/earth/thirst.m4a" },
            { word: "turf", audio: "audio/earth/turf.m4a" },
            { word: "turn", audio: "audio/earth/turn.m4a" },
            { word: "verse", audio: "audio/earth/verse.m4a" },
            { word: "worst", audio: "audio/earth/worst.m4a" },
            { word: "yearn", audio: "audio/earth/yearn.m4a" },
            { word: "birth", audio: "audio/earth/birth.m4a" },
            { word: "burn", audio: "audio/earth/burn.m4a" },
            { word: "chirp", audio: "audio/earth/chirp.m4a" }
        ],
        image: "images/vowel_card_earth.jpg"
    },

    // Elephant - short "e" sound /e/
    {
        name: "elephant",
        symbol: "e",
        vowelAudio: "audio/elephant/e.m4a",
        words: [
            // *** CRITICAL ADDITION ***
            { word: "vowel sound", audio: "audio/elephant/elephant_vowel_sound_only.m4a" },
            { word: "fetch", audio: "audio/elephant/fetch.m4a" },
            { word: "get", audio: "audio/elephant/get.m4a" },
            { word: "head", audio: "audio/elephant/head.m4a" },
            { word: "jet", audio: "audio/elephant/jet.m4a" },
            { word: "keg", audio: "audio/elephant/keg.m4a" },
            { word: "lend", audio: "audio/elephant/lend.m4a" },
            { word: "let", audio: "audio/elephant/let.m4a" },
            { word: "men", audio: "audio/elephant/men.m4a" },
            { word: "next", audio: "audio/elephant/next.m4a" },
            { word: "pen", audio: "audio/elephant/pen.m4a" },
            { word: "quest", audio: "audio/elephant/quest.m4a" },
            { word: "red", audio: "audio/elephant/red.m4a" },
            { word: "said", audio: "audio/elephant/said.m4a" },
            { word: "shed", audio: "audio/elephant/shed.m4a" },
            { word: "tell", audio: "audio/elephant/tell.m4a" },
            { word: "then", audio: "audio/elephant/then.m4a" },
            { word: "vent", audio: "audio/elephant/vent.m4a" },
            { word: "bed", audio: "audio/elephant/bed.m4a" },
            { word: "dead", audio: "audio/elephant/dead.m4a" },
            { word: "fetch", audio: "audio/elephant/fetch.m4a" },
            { word: "keg", audio: "audio/elephant/keg.m4a" },
            { word: "when", audio: "audio/elephant/when.m4a" },
            { word: "yes", audio: "audio/elephant/yes.m4a" },
            { word: "zed", audio: "audio/elephant/zed.m4a" },
            { word: "check", audio: "audio/elephant/check.m4a" },
            { word: "e", audio: "audio/elephant/e.m4a" },
            { word: "egg", audio: "audio/elephant/egg.m4a" }
        ],
        image: "images/vowel_card_elephant.jpg"
    },

    // Foot - "oo" sound /ʊ/
    {
        name: "foot",
        symbol: "ʊ",
        vowelAudio: "audio/foot/u.m4a",
        words: [
            // *** CRITICAL ADDITION ***
            { word: "vowel sound", audio: "audio/foot/foot_vowel_sound_only.m4a" },
            { word: "good", audio: "audio/foot/good.m4a" },
            { word: "hood", audio: "audio/foot/hood.m4a" },
            { word: "hook", audio: "audio/foot/hook.m4a" },
            { word: "look", audio: "audio/foot/look.m4a" },
            { word: "nook", audio: "audio/foot/nook.m4a" },
            { word: "put", audio: "audio/foot/put.m4a" },
            { word: "rook", audio: "audio/foot/rook.m4a" },
            { word: "shook", audio: "audio/foot/shook.m4a" },
            { word: "should", audio: "audio/foot/should.m4a" },
            { word: "stood", audio: "audio/foot/stood.m4a" },
            { word: "took", audio: "audio/foot/took.m4a" },
            { word: "u", audio: "audio/foot/u.m4a" },
            { word: "vulf", audio: "audio/foot/vulf.m4a" },
            { word: "wolf", audio: "audio/foot/wolf.m4a" },
            { word: "wood", audio: "audio/foot/wood.m4a" },
            { word: "book", audio: "audio/foot/book.m4a" },
            { word: "bull", audio: "audio/foot/bull.m4a" },
            { word: "bush", audio: "audio/foot/bush.m4a" },
            { word: "cook", audio: "audio/foot/cook.m4a" },
            { word: "foot", audio: "audio/foot/foot.m4a" }
        ],
        image: "images/vowel_card_foot.jpg"
    },

    // Icecream - long "i" sound /aɪ/
    {
        name: "icecream",
        symbol: "aɪ",
        vowelAudio: "audio/icecream/ie.m4a",
        words: [
            // *** CRITICAL ADDITION ***
            { word: "vowel sound", audio: "audio/icecream/icecream_vowel_sound_only.m4a" },
            { word: "ice", audio: "audio/icecream/ice.m4a" },
            { word: "ie", audio: "audio/icecream/ie.m4a" },
            { word: "im", audio: "audio/icecream/im.m4a" },
            { word: "jibe", audio: "audio/icecream/jibe.m4a" },
            { word: "kite", audio: "audio/icecream/kite.m4a" },
            { word: "life", audio: "audio/icecream/life.m4a" },
            { word: "mice", audio: "audio/icecream/mice.m4a" },
            { word: "nine", audio: "audio/icecream/nine.m4a" },
            { word: "pine", audio: "audio/icecream/pine.m4a" },
            { word: "pint", audio: "audio/icecream/pint.m4a" },
            { word: "quite", audio: "audio/icecream/quite.m4a" },
            { word: "rhyme", audio: "audio/icecream/rhyme.m4a" },
            { word: "rice", audio: "audio/icecream/rice.m4a" },
            { word: "shy", audio: "audio/icecream/shy.m4a" },
            { word: "side", audio: "audio/icecream/side.m4a" },
            { word: "thigh", audio: "audio/icecream/thigh.m4a" },
            { word: "time", audio: "audio/icecream/time.m4a" },
            { word: "vice", audio: "audio/icecream/vice.m4a" },
            { word: "vine", audio: "audio/icecream/vine.m4a" },
            { word: "wine", audio: "audio/icecream/wine.m4a" },
            { word: "bike", audio: "audio/icecream/bike.m4a" },
            { word: "chime", audio: "audio/icecream/chime.m4a" },
            { word: "die", audio: "audio/icecream/die.m4a" },
            { word: "dike", audio: "audio/icecream/dike.m4a" },
            { word: "fight", audio: "audio/icecream/fight.m4a" },
            { word: "guy", audio: "audio/icecream/guy.m4a" },
            { word: "height", audio: "audio/icecream/height.m4a" }
        ],
        image: "images/vowel_card_icecream.jpg"
    },

    // Ocean - long "o" sound /oʊ/
    {
        name: "ocean",
        symbol: "oʊ",
        vowelAudio: "audio/ocean/oh.m4a",
        words: [
            // *** CRITICAL ADDITION ***
            { word: "vowel sound", audio: "audio/ocean/ocean_vowel_sound_only.m4a" },
            { word: "flow", audio: "audio/ocean/flow.m4a" },
            { word: "goat", audio: "audio/ocean/goat.m4a" },
            { word: "host", audio: "audio/ocean/host.m4a" },
            { word: "joke", audio: "audio/ocean/joke.m4a" },
            { word: "loan", audio: "audio/ocean/loan.m4a" },
            { word: "mope", audio: "audio/ocean/mope.m4a" },
            { word: "note", audio: "audio/ocean/note.m4a" },
            { word: "oh", audio: "audio/ocean/oh.m4a" },
            { word: "own", audio: "audio/ocean/own.m4a" },
            { word: "poke", audio: "audio/ocean/poke.m4a" },
            { word: "quote", audio: "audio/ocean/quote.m4a" },
            { word: "rope", audio: "audio/ocean/rope.m4a" },
            { word: "show", audio: "audio/ocean/show.m4a" },
            { word: "soak", audio: "audio/ocean/soak.m4a" },
            { word: "though", audio: "audio/ocean/though.m4a" },
            { word: "told", audio: "audio/ocean/told.m4a" },
            { word: "tote", audio: "audio/ocean/tote.m4a" },
            { word: "vote", audio: "audio/ocean/vote.m4a" },
            { word: "woke", audio: "audio/ocean/woke.m4a" },
            { word: "yo", audio: "audio/ocean/yo.m4a" },
            { word: "zone", audio: "audio/ocean/zone.m4a" },
            { word: "bold", audio: "audio/ocean/bold.m4a" },
            { word: "bone", audio: "audio/ocean/bone.m4a" },
            { word: "choke", audio: "audio/ocean/choke.m4a" },
            { word: "coat", audio: "audio/ocean/coat.m4a" },
            { word: "dont", audio: "audio/ocean/dont.m4a" }
        ],
        image: "images/vowel_card_ocean.jpg"
    },

    // Oil - "oi" sound /ɔɪ/
    {
        name: "oil",
        symbol: "ɔɪ",
        vowelAudio: "audio/oil/oi.m4a",
        words: [
            // *** CRITICAL ADDITION ***
            { word: "vowel sound", audio: "audio/oil/oil_vowel_sound_only.m4a" },
            { word: "oi", audio: "audio/oil/oi.m4a" },
            { word: "oil", audio: "audio/oil/oil.m4a" },
            { word: "poise", audio: "audio/oil/poise.m4a" },
            { word: "roy", audio: "audio/oil/roy.m4a" },
            { word: "royal", audio: "audio/oil/royal.m4a" },
            { word: "soy", audio: "audio/oil/soy.m4a" },
            { word: "toy", audio: "audio/oil/toy.m4a" },
            { word: "void", audio: "audio/oil/void.m4a" },
            { word: "boy", audio: "audio/oil/boy.m4a" },
            { word: "choice", audio: "audio/oil/choice.m4a" },
            { word: "coin", audio: "audio/oil/coin.m4a" },
            { word: "doyle", audio: "audio/oil/doyle.m4a" },
            { word: "foil", audio: "audio/oil/foil.m4a" },
            { word: "joy", audio: "audio/oil/joy.m4a" },
            { word: "loin", audio: "audio/oil/loin.m4a" },
            { word: "moist", audio: "audio/oil/moist.m4a" },
            { word: "noise", audio: "audio/oil/noise.m4a" }
        ],
        image: "images/vowel_card_oil.jpg"
    },

    // Ostrich - short "o" sound /ɑ/
    {
        name: "ostrich",
        symbol: "ɑ",
        vowelAudio: "audio/ostrich/a.m4a",
        words: [
            // *** CRITICAL ADDITION ***
            { word: "vowel sound", audio: "audio/ostrich/ostrich_vowel_sound_only.m4a" },
            { word: "got", audio: "audio/ostrich/got.m4a" },
            { word: "hot", audio: "audio/ostrich/hot.m4a" },
            { word: "jot", audio: "audio/ostrich/jot.m4a" },
            { word: "lox", audio: "audio/ostrich/lox.m4a" },
            { word: "mop", audio: "audio/ostrich/mop.m4a" },
            { word: "nox", audio: "audio/ostrich/nox.m4a" },
            { word: "ox", audio: "audio/ostrich/ox.m4a" },
            { word: "pot", audio: "audio/ostrich/pot.m4a" },
            { word: "quad", audio: "audio/ostrich/quad.m4a" },
            { word: "rock", audio: "audio/ostrich/rock.m4a" },
            { word: "saab", audio: "audio/ostrich/saab.m4a" },
            { word: "shock", audio: "audio/ostrich/shock.m4a" },
            { word: "talk", audio: "audio/ostrich/talk.m4a" },
            { word: "thaa", audio: "audio/ostrich/thaa.m4a" },
            { word: "vox", audio: "audio/ostrich/vox.m4a" },
            { word: "watch", audio: "audio/ostrich/watch.m4a" },
            { word: "yacht", audio: "audio/ostrich/yacht.m4a" },
            { word: "a", audio: "audio/ostrich/a.m4a" },
            { word: "box", audio: "audio/ostrich/box.m4a" },
            { word: "chalk", audio: "audio/ostrich/chalk.m4a" },
            { word: "cot", audio: "audio/ostrich/cot.m4a" },
            { word: "dot", audio: "audio/ostrich/dot.m4a" },
            { word: "fox", audio: "audio/ostrich/fox.m4a" }
        ],
        image: "images/vowel_card_ostrich.jpg"
    },

    // Owl - "ow" sound /aʊ/
    {
        name: "owl",
        symbol: "aʊ",
        vowelAudio: "audio/owl/ao.m4a",
        words: [
            // *** CRITICAL ADDITION ***
            { word: "vowel sound", audio: "audio/owl/owl_vowel_sound_only.m4a" },
            { word: "loud", audio: "audio/owl/loud.m4a" },
            { word: "mouse", audio: "audio/owl/mouse.m4a" },
            { word: "mouth", audio: "audio/owl/mouth.m4a" },
            { word: "now", audio: "audio/owl/now.m4a" },
            { word: "ouch", audio: "audio/owl/ouch.m4a" },
            { word: "our", audio: "audio/owl/our.m4a" },
            { word: "out", audio: "audio/owl/out.m4a" },
            { word: "pow", audio: "audio/owl/pow.m4a" },
            { word: "round", audio: "audio/owl/round.m4a" },
            { word: "shout", audio: "audio/owl/shout.m4a" },
            { word: "sound", audio: "audio/owl/sound.m4a" },
            { word: "thou", audio: "audio/owl/thou.m4a" },
            { word: "town", audio: "audio/owl/town.m4a" },
            { word: "vow", audio: "audio/owl/vow.m4a" },
            { word: "wow", audio: "audio/owl/wow.m4a" },
            { word: "ao", audio: "audio/owl/ao.m4a" },
            { word: "bow", audio: "audio/owl/bow.m4a" },
            { word: "chow", audio: "audio/owl/chow.m4a" },
            { word: "cow", audio: "audio/owl/cow.m4a" },
            { word: "doubt", audio: "audio/owl/doubt.m4a" },
            { word: "found", audio: "audio/owl/found.m4a" },
            { word: "gown", audio: "audio/owl/gown.m4a" },
            { word: "house", audio: "audio/owl/house.m4a" },
            { word: "joust", audio: "audio/owl/joust.m4a" }
        ],
        image: "images/vowel_card_owl.jpg"
    },

    // Pin - short "i" sound /ɪ/
    {
        name: "pin",
        symbol: "ɪ",
        vowelAudio: "audio/pin/i.m4a",
        words: [
            // *** CRITICAL ADDITION ***
            { word: "vowel sound", audio: "audio/pin/pin_vowel_sound_only.m4a" },
            { word: "i", audio: "audio/pin/i.m4a" },
            { word: "it", audio: "audio/pin/it.m4a" },
            { word: "kick", audio: "audio/pin/kick.m4a" },
            { word: "knit", audio: "audio/pin/knit.m4a" },
            { word: "lip", audio: "audio/pin/lip.m4a" },
            { word: "mix", audio: "audio/pin/mix.m4a" },
            { word: "pinch", audio: "audio/pin/pinch.m4a" },
            { word: "quiz", audio: "audio/pin/quiz.m4a" },
            { word: "risk", audio: "audio/pin/risk.m4a" },
            { word: "ship", audio: "audio/pin/ship.m4a" },
            { word: "sip", audio: "audio/pin/sip.m4a" },
            { word: "thin", audio: "audio/pin/thin.m4a" },
            { word: "till", audio: "audio/pin/till.m4a" },
            { word: "vick", audio: "audio/pin/vick.m4a" },
            { word: "big", audio: "audio/pin/big.m4a" },
            { word: "chips", audio: "audio/pin/chips.m4a" },
            { word: "dip", audio: "audio/pin/dip.m4a" },
            { word: "fish", audio: "audio/pin/fish.m4a" },
            { word: "wish", audio: "audio/pin/wish.m4a" },
            { word: "zip", audio: "audio/pin/zip.m4a" },
            { word: "chick", audio: "audio/pin/chick.m4a" },
            { word: "dinner", audio: "audio/pin/dinner.m4a" },
            { word: "give", audio: "audio/pin/give.m4a" },
            { word: "gym", audio: "audio/pin/gym.m4a" },
            { word: "hit", audio: "audio/pin/hit.m4a" }
        ],
        image: "images/vowel_card_pin.jpg"
    },

    // Ukulele - long "oo" sound /u/
    {
        name: "ukulele",
        symbol: "u",
        vowelAudio: "audio/ukulele/uu.m4a",
        words: [
            // *** CRITICAL ADDITION ***
            { word: "vowel sound", audio: "audio/ukulele/ukulele_vowel_sound_only.m4a" },
            { word: "mooch", audio: "audio/ukulele/mooch.m4a" },
            { word: "new", audio: "audio/ukulele/new.m4a" },
            { word: "oof", audio: "audio/ukulele/oof.m4a" },
            { word: "pooch", audio: "audio/ukulele/pooch.m4a" },
            { word: "rude", audio: "audio/ukulele/rude.m4a" },
            { word: "rune", audio: "audio/ukulele/rune.m4a" },
            { word: "shoe", audio: "audio/ukulele/shoe.m4a" },
            { word: "soup", audio: "audio/ukulele/soup.m4a" },
            { word: "threw", audio: "audio/ukulele/threw.m4a" },
            { word: "two", audio: "audio/ukulele/two.m4a" },
            { word: "uu", audio: "audio/ukulele/uu.m4a" },
            { word: "who", audio: "audio/ukulele/who.m4a" },
            { word: "wooh", audio: "audio/ukulele/wooh.m4a" },
            { word: "you", audio: "audio/ukulele/you.m4a" },
            { word: "zoo", audio: "audio/ukulele/zoo.m4a" },
            { word: "boots", audio: "audio/ukulele/boots.m4a" },
            { word: "choose", audio: "audio/ukulele/choose.m4a" },
            { word: "cute", audio: "audio/ukulele/cute.m4a" },
            { word: "do", audio: "audio/ukulele/do.m4a" },
            { word: "food", audio: "audio/ukulele/food.m4a" },
            { word: "goo", audio: "audio/ukulele/goo.m4a" },
            { word: "hoop", audio: "audio/ukulele/hoop.m4a" },
            { word: "june", audio: "audio/ukulele/june.m4a" },
            { word: "luke", audio: "audio/ukulele/luke.m4a" }
        ],
        image: "images/vowel_card_ukelele.jpg"
    },

    // Umbrella - short "u" sound /ʌ/
    {
        name: "umbrella",
        symbol: "ʌ",
        vowelAudio: "audio/umbrella/uh.m4a",
        words: [
            // *** CRITICAL ADDITION ***
            { word: "vowel sound", audio: "audio/umbrella/umbrella_vowel_sound_only.m4a" },
            { word: "punch", audio: "audio/umbrella/punch.m4a" },
            { word: "run", audio: "audio/umbrella/run.m4a" },
            { word: "shush", audio: "audio/umbrella/shush.m4a" },
            { word: "sun", audio: "audio/umbrella/sun.m4a" },
            { word: "the", audio: "audio/umbrella/the.m4a" },
            { word: "tug", audio: "audio/umbrella/tug.m4a" },
            { word: "uh", audio: "audio/umbrella/uh.m4a" },
            { word: "up", audio: "audio/umbrella/up.m4a" },
            { word: "us", audio: "audio/umbrella/us.m4a" },
            { word: "what", audio: "audio/umbrella/what.m4a" },
            { word: "young", audio: "audio/umbrella/young.m4a" },
            { word: "bug", audio: "audio/umbrella/bug.m4a" },
            { word: "chug", audio: "audio/umbrella/chug.m4a" },
            { word: "cup", audio: "audio/umbrella/cup.m4a" },
            { word: "dug", audio: "audio/umbrella/dug.m4a" },
            { word: "fun", audio: "audio/umbrella/fun.m4a" },
            { word: "fuzz", audio: "audio/umbrella/fuzz.m4a" },
            { word: "guts", audio: "audio/umbrella/guts.m4a" },
            { word: "hutch", audio: "audio/umbrella/hutch.m4a" },
            { word: "jug", audio: "audio/umbrella/jug.m4a" },
            { word: "lunch", audio: "audio/umbrella/lunch.m4a" },
            { word: "mutt", audio: "audio/umbrella/mutt.m4a" },
            { word: "nut", audio: "audio/umbrella/nut.m4a" }
        ],
        image: "images/vowel_card_umbrella.jpg"
    }
];